# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_ip_source/Arty_TDC_ip_source.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
# IP: The module: 'axi_bram_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_ip_source/Arty_TDC_ip_source.gen/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram_ctrl_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_ip_source/Arty_TDC_ip_source.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
# IP: The module: 'axi_bram_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_ip_source/Arty_TDC_ip_source.gen/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram_ctrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
