domain_path: C:\Users\alumn\Documents\UNSAM\PFI\TDC\Full_TDC_Project\All_Vitis\platform_v03\export\platform_v03\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
