# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Quick_tests/MicroBlazeTest/MicroBlazeTest.srcs/sources_1/bd/system/ip/system_rst_mig_7series_0_81M_1/system_rst_mig_7series_0_81M_1.xci
# IP: The module: 'system_rst_mig_7series_0_81M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Quick_tests/MicroBlazeTest/MicroBlazeTest.gen/sources_1/bd/system/ip/system_rst_mig_7series_0_81M_1/system_rst_mig_7series_0_81M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_mig_7series_0_81M_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Quick_tests/MicroBlazeTest/MicroBlazeTest.gen/sources_1/bd/system/ip/system_rst_mig_7series_0_81M_1/system_rst_mig_7series_0_81M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_mig_7series_0_81M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Quick_tests/MicroBlazeTest/MicroBlazeTest.gen/sources_1/bd/system/ip/system_rst_mig_7series_0_81M_1/system_rst_mig_7series_0_81M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_mig_7series_0_81M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Quick_tests/MicroBlazeTest/MicroBlazeTest.srcs/sources_1/bd/system/ip/system_rst_mig_7series_0_81M_1/system_rst_mig_7series_0_81M_1.xci
# IP: The module: 'system_rst_mig_7series_0_81M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Quick_tests/MicroBlazeTest/MicroBlazeTest.gen/sources_1/bd/system/ip/system_rst_mig_7series_0_81M_1/system_rst_mig_7series_0_81M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_mig_7series_0_81M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Quick_tests/MicroBlazeTest/MicroBlazeTest.gen/sources_1/bd/system/ip/system_rst_mig_7series_0_81M_1/system_rst_mig_7series_0_81M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_mig_7series_0_81M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Quick_tests/MicroBlazeTest/MicroBlazeTest.gen/sources_1/bd/system/ip/system_rst_mig_7series_0_81M_1/system_rst_mig_7series_0_81M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_mig_7series_0_81M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
