domain_path: C:\Users\alumn\Documents\UNSAM\PFI\Arty_TDC\Vitis_WorkSpace\platform_tdc\export\platform_tdc\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
