# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.srcs/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/system_Arty_AXITDC_0_0.xci
# IP: The module: 'system_Arty_AXITDC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] -quiet

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0_ooc.xdc

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/Arty-A7-35-Master-clean.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Arty_AXITDC_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.srcs/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/system_Arty_AXITDC_0_0.xci
# IP: The module: 'system_Arty_AXITDC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] -quiet

# IP: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0_ooc.xdc

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/axi_gpio_0/axi_gpio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Users/alumn/Documents/UNSAM/PFI/TDC/Full_TDC_Project/Arty_TDC_v05/Arty_TDC_v05.gen/sources_1/bd/system/ip/system_Arty_AXITDC_0_0/src/Arty-A7-35-Master-clean.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Arty_AXITDC_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
